[2024-05-21T16:20:53.866+0530] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-21T16:20:53.880+0530] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_dag.load_task manual__2024-05-21T09:12:34.180878+00:00 [queued]>
[2024-05-21T16:20:53.883+0530] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_dag.load_task manual__2024-05-21T09:12:34.180878+00:00 [queued]>
[2024-05-21T16:20:53.883+0530] {taskinstance.py:2306} INFO - Starting attempt 2 of 3
[2024-05-21T16:20:53.943+0530] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load_task> on 2024-05-21 09:12:34.180878+00:00
[2024-05-21T16:20:53.946+0530] {standard_task_runner.py:63} INFO - Started process 87815 to run task
[2024-05-21T16:20:53.948+0530] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'etl_dag', 'load_task', 'manual__2024-05-21T09:12:34.180878+00:00', '--job-id', '48', '--raw', '--subdir', 'DAGS_FOLDER/etl_dag.py', '--cfg-path', '/tmp/tmpg0ueaz29']
[2024-05-21T16:20:53.949+0530] {standard_task_runner.py:91} INFO - Job 48: Subtask load_task
[2024-05-21T16:20:54.029+0530] {task_command.py:426} INFO - Running <TaskInstance: etl_dag.load_task manual__2024-05-21T09:12:34.180878+00:00 [running]> on host prince-5192
[2024-05-21T16:20:54.127+0530] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='prince.yadav@tothenew.com' AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='etl_dag' AIRFLOW_CTX_TASK_ID='load_task' AIRFLOW_CTX_EXECUTION_DATE='2024-05-21T09:12:34.180878+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-21T09:12:34.180878+00:00'
[2024-05-21T16:20:54.127+0530] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-21T16:20:54.134+0530] {logging_mixin.py:188} INFO - /////////////////// 	 Loading started 	///////////////////////////
[2024-05-21T16:20:54.135+0530] {logging_mixin.py:188} INFO - /////////////////// 	 Pulling data from xcomm 	///////////////////////////
[2024-05-21T16:20:54.139+0530] {logging_mixin.py:188} INFO - /////////////////// 	 Making connection to s3 	///////////////////////////
[2024-05-21T16:20:54.148+0530] {base.py:84} INFO - Using connection ID 'aws_default' for task execution.
[2024-05-21T16:20:54.149+0530] {connection_wrapper.py:384} INFO - AWS Connection (conn_id='aws_default', conn_type='aws') credentials retrieved from login and password.
[2024-05-21T16:21:11.175+0530] {logging_mixin.py:188} INFO - /////////////////// 	 Data Saved to S3 Bucket	///////////////////////////
[2024-05-21T16:21:11.176+0530] {python.py:237} INFO - Done. Returned value was: None
[2024-05-21T16:21:11.176+0530] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-21T16:21:11.179+0530] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=etl_dag, task_id=load_task, run_id=manual__2024-05-21T09:12:34.180878+00:00, execution_date=20240521T091234, start_date=20240521T105053, end_date=20240521T105111
[2024-05-21T16:21:11.301+0530] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-21T16:21:11.309+0530] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-05-21T16:21:11.353+0530] {local_task_job_runner.py:222} INFO - ::endgroup::
